# Generated by Django 3.0.6 on 2020-05-05 21:16

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('Image', wagtail.images.blocks.ImageChooserBlock()), ('raw_html', wagtail.core.blocks.RawHTMLBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('block_quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(label='Body', required=True)), ('color', wagtail.core.blocks.StructBlock([('background_image', wagtail.images.blocks.ImageChooserBlock(help_text='This image, if supplied, will appear as a background for this block', required=False)), ('background_color', wagtail.core.blocks.ChoiceBlock(blank=False, choices=[(None, 'Transparent'), ('white', 'White'), ('black', 'Black'), ('orange', 'Orange'), ('ltgray', 'Light Gray'), ('midgray', 'Mid Gray'), ('darkergray', 'Dark Gray'), ('dkgray', 'Very Dark Gray'), ('olivegreen', 'Olive Green'), ('purple', 'Purple'), ('darkteal', 'Dark Teal')], help_text='Set the background color of this block.  If a Background Image is also supplied, the Background Image will be displayed instead of this color', required=False)), ('text_color', wagtail.core.blocks.ChoiceBlock(blank=False, choices=[(None, 'Default'), ('dkgray', 'Dark Gray'), ('black', 'Black'), ('white', 'White')], help_text='Set the color for the text in this block. This is here so you can make your text visible on both light and dark backgrounds.', required=False))])), ('fixed_dimensions', wagtail.core.blocks.StructBlock([('use', wagtail.core.blocks.BooleanBlock(default=False, help_text='Normally, the image will expand its height to satisfy the suggested height on its parent block. Checking this box will make it conform to the specified height and width, instead.', label='Use Fixed Dimensions', required=False)), ('height', wagtail.core.blocks.IntegerBlock(default=200, help_text='If "Fixed Dimensions" is checked, or if this block is placed outside a layout element (e.g. outside a N-Column "layout), set the image to be this many pixels tall.', label='Height (pixels)')), ('width', wagtail.core.blocks.IntegerBlock(default=200, help_text='If "Fixed Dimensions" is checked, or if this block is placed outside a layout element (e.g. outside a N-Column layout), set the image to be this many pixels wide.', label='Width (pixels)'))]))])), ('two_column_block', wagtail.core.blocks.StreamBlock([])), ('four_column_block', wagtail.core.blocks.ChoiceBlock(choices=[])), ('link_block', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock(help_text='Link to the chosen page. If a Page is selected, it will take precedence over both.', required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(help_text='Link to the chosen document. If a document is selected, it will take precedence over a URL.', required=False)), ('url', wagtail.core.blocks.CharBlock(help_text='Link to the given URL. This can be a relative URL to a location your own site (e.g. /example-page) or an absolute URL to a page on another site (e.g. http://www.caltech.edu). Note: absolute URLs must include the http:// otherwise they will not work.', required=False))]))], blank=True, null=True),
        ),
    ]
