# Generated by Django 3.0.6 on 2020-05-08 09:01

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200508_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('image_slider', wagtail.core.blocks.StructBlock([('slides', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('slide', wagtail.core.blocks.StructBlock([('bg_type', wagtail.core.blocks.ChoiceBlock(blank=False, choices=[('bg-0', 'bg-0'), ('bg-1', 'bg-1'), ('bg-2', 'bg-2'), ('bg-3', 'bg-3'), ('bg-4', 'bg-4'), ('bg-5', 'bg-5'), ('bg-6', 'bg-6'), ('bg-7', 'bg-7'), ('bg-8', 'bg-8'), ('bg-9', 'bg-9'), ('bg-10', 'bg-10'), ('bg-11', 'bg-11'), ('bg-12', 'bg-12'), ('bg-13', 'bg-13'), ('bg-14', 'bg-14'), ('bg-15', 'bg-15'), ('bg-16', 'bg-16'), ('bg-17', 'bg-17'), ('bg-18', 'bg-18'), ('bg-19', 'bg-19'), ('bg-20', 'bg-20'), ('bg-rounded1', 'bg-rounded1'), ('bg-rounded2', 'bg-rounded2'), ('bg-rounded3', 'bg-rounded3'), ('bg-rounded4', 'bg-rounded4')], help_text='Set Slide BG according to docs')), ('heading', wagtail.core.blocks.CharBlock(max_length=50, required=True)), ('text', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image dimension needs to be XXXXX', required=False))]))])))])), ('info_block1', wagtail.core.blocks.StructBlock([('boxes', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('text', wagtail.core.blocks.TextBlock(max_length=400, required=True)), ('svg_icon', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('alarm', '/img/svg_icons/alarm'), ('calendar', '/img/svg_icons/calendar'), ('chat', '/img/svg_icons/chat'), ('chat_multi', '/img/svg_icons/chat_multi'), ('clock', '/img/svg_icons/clock'), ('cloud-computing', '/img/svg_icons/cloud-computing'), ('cup', '/img/svg_icons/cup'), ('devices', '/img/svg_icons/devices'), ('dial', '/img/svg_icons/dial'), ('finger_tap', '/img/svg_icons/finger_tap'), ('fingerprint', '/img/svg_icons/fingerprint'), ('flag', '/img/svg_icons/flag'), ('google-play', '/img/svg_icons/google-play'), ('library', '/img/svg_icons/library'), ('link', '/img/svg_icons/link'), ('music', '/img/svg_icons/music'), ('payment-method', '/img/svg_icons/payment-method'), ('pictures', '/img/svg_icons/pictures'), ('rocket', '/img/svg_icons/rocket'), ('settings', '/img/svg_icons/settings'), ('shirt', '/img/svg_icons/shirt'), ('smartphones', '/img/svg_icons/smartphones')], help_text='Choose your')), ('url', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock(help_text='Link to the chosen page. If a Page is selected, it will take precedence over both.', required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(help_text='Link to the chosen document. If a document is selected, it will take precedence over a URL.', required=False)), ('url', wagtail.core.blocks.CharBlock(help_text='Link to the given URL. This can be a relative URL to a location your own site (e.g. /example-page) or an absolute URL to a page on another site (e.g. http://www.caltech.edu). Note: absolute URLs must include the http:// otherwise they will not work.', required=False))], required=False))])))]))], blank=True, null=True),
        ),
    ]
