# Generated by Django 3.0.6 on 2020-05-10 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_client_clientsorderable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Client'},
        ),
    ]
