# Generated by Django 3.0.6 on 2020-05-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20200510_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.RenameField(
            model_name='clientsorderable',
            old_name='author',
            new_name='client',
        ),
    ]
