# Generated by Django 3.0.6 on 2020-05-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20200512_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsorderable',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientsorderable',
            name='page',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='ClientsOrderable',
        ),
    ]
