# Generated by Django 3.0.6 on 2020-05-14 11:26

import datetime
from django.db import migrations, models
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Writing Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='writingpostpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='writingpostpage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Post date'),
        ),
        migrations.AddField(
            model_name='writingpostpage',
            name='excerpt',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=1000, verbose_name='excerpt'),
        ),
        migrations.AddField(
            model_name='writingpostpage',
            name='writing_categories',
            field=modelcluster.fields.ParentalManyToManyField(to='writings.WritingCategory'),
        ),
    ]
