# Generated by Django 3.0.6 on 2020-05-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0006_auto_20200515_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writingpostpage',
            old_name='video',
            new_name='video_url',
        ),
    ]
