# Generated by Django 3.0.6 on 2020-05-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('writings', '0007_auto_20200515_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingpostpage',
            name='video_thumb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
