# Generated by Django 3.0.6 on 2020-05-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0008_auto_20200515_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
